name: flutter_kasir
description: A new Flutter project.

publish_to: 'none'

version: 1.8.10+17

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  # Functional programming thingies
  dartz: ^0.10.1
  # Value equality
  equatable: ^2.0.3
  # Networking
  dio: ^4.0.4
  # Bloc for state management
  flutter_bloc: ^7.3.0
  # Service locator
  get_it: ^7.2.0
  injectable: ^1.5.3
  # GetX for route, state & dependency management
  get: ^4.6.5
  # Like kotlin sealed class
  freezed_annotation: ^1.1.0
  # Responsive UI util
  flutter_screenutil: ^5.3.1
  # SVG image
  flutter_svg: ^1.0.3
  # Form builder helper
  flutter_form_builder: ^6.1.0+1
  # Staggered grid view
  flutter_staggered_grid_view: ^0.4.0
  # No SQL local storage
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  # Cached network image
  cached_network_image: ^3.2.0
  # Image picker
  image_picker: ^0.8.4+10
  # Permission handler
  permission_handler: ^9.2.0
  # Localization / date / number
  intl: ^0.17.0
  # Thermal printer bluetooth integration
  esc_pos_utils: ^1.1.0
  esc_pos_bluetooth:
    path: plugins/esc_pos_bluetooth
  # Icon bundles
  font_awesome_flutter: ^9.2.0
  # Remote logging
  flutter_bugfender: ^2.0.1
  # Keyboard visibility handler
  flutter_keyboard_visibility: ^5.2.0
  # Debouncer
  easy_debounce: ^2.0.2+1
  # Alternative of StatefulWidget to reduce boilerplate
  flutter_hooks: ^0.18.2+1
  month_picker_dialog: ^0.4.0
  js:
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  # flutter pub run build_runner build --delete-conflicting-outputs
  build_runner: ^2.1.7
  freezed: ^1.1.1
  json_serializable: ^6.1.4
  hive_generator: ^1.1.2
  # Service locator
  injectable_generator: ^1.5.3
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/ic_ms_glow.png"
